<?php
/**
 * OrderStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  OGOship
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OGOship API
 *
 * Description
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tech@ogoship.zendesk.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace OGOship\Models;
use \OGOship\ObjectSerializer;

/**
 * OrderStatus Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  OGOship
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderStatus
{
    /**
     * Possible values of this enum
     */
    const DRAFT = 'draft';
    const RESERVED = 'reserved';
    const _NEW = 'new';
    const LOCKED = 'locked';
    const COLLECTING = 'collecting';
    const PENDING = 'pending';
    const CANCELLED = 'cancelled';
    const SHIPPED = 'shipped';
    const RETURNED = 'returned';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
            self::RESERVED,
            self::_NEW,
            self::LOCKED,
            self::COLLECTING,
            self::PENDING,
            self::CANCELLED,
            self::SHIPPED,
            self::RETURNED,
        ];
    }
}


